### ISSUE TITLE
Helm installation fails using FlexCD.

### ISSUE THREAD

**Issue by chattytak** [enix/kube-image-keeper#437] opened 2024-11-11 14:53 UTC
The CronJob “kube-image-keeper-registry-garbage-collection” has too long a name, and prefixing it with Namespace would exceed the 52 character limit.
This is not a problem with kuik, but could the name be changed to something shorter, for example, “kuik-registry-garbage-collection”?

```
Warning  InstallFailed       8s                     helm-controller  Helm install failed for release kuik-system/kuik-system-kube-image-keeper with chart kube-image-keeper@1.10.0:
 1 error occurred: * CronJob.batch "kuik-system-kube-image-keeper-registry-garbage-collection" is invalid: 
metadata.name: Invalid value: "kuik-system-kube-image-keeper-registry-garbage-collection": must be no more than 52 characters
```

**Comment by paullaffitte** [comment] 2024-11-15 13:39
duplicate of #425, closing

**Closed by paullaffitte** 2024-11-15 13:39 UTC
