### ISSUE TITLE
Error on reconcile when source image was deleted

### ISSUE THREAD

**Issue by roni-frantchi** [enix/kube-image-keeper#66] opened 2023-04-04 05:42 UTC
I believe the following are the steps to reproduce:  
1. Run a pod with image X, to completion
2. Delete the source image
3. Restart kuik's pods (persistence is turned on, pvc attached)
4. Run `kubectl annotate cachedimages --all --overwrite "timestamp=$(date +%s)"`
5. Controller repeatedly fails with the following:

```
2023-04-04T05:34:25.004Z	INFO	controller-runtime.manager.controller.cachedimage	reconciling cachedimage	{"reconciler group": "kuik.enix.io", "reconciler kind": "CachedImage", "name": "ghcr.io-env0-deployment-service-pr11529-sha-532aabb", "namespace": ""}
2023-04-04T05:34:25.004Z	INFO	controller-runtime.manager.controller.cachedimage	caching image	{"reconciler group": "kuik.enix.io", "reconciler kind": "CachedImage", "name": "ghcr.io-env0-deployment-service-pr11529-sha-532aabb", "namespace": "", "sourceImage": "ghcr.io/env0/deployment-service:pr11529-sha-532aabb"}
2023-04-04T05:34:27.790Z	INFO	controller-runtime.manager.controller.pod	reconciling pod	{"reconciler group": "", "reconciler kind": "Pod", "name": "env0-6qklp-jf98p", "namespace": "env0-agent-pr11529"}
2023-04-04T05:34:27.801Z	INFO	controller-runtime.manager.controller.pod	cachedimage patched	{"reconciler group": "", "reconciler kind": "Pod", "name": "env0-6qklp-jf98p", "namespace": "env0-agent-pr11529", "cachedImage": "ghcr.io-env0-deployment-service-pr11529-sha-532aabb", "sourceImage": "ghcr.io/env0/deployment-service:pr11529-sha-532aabb"}
2023-04-04T05:34:27.801Z	INFO	controller-runtime.manager.controller.pod	reconciled pod	{"reconciler group": "", "reconciler kind": "Pod", "name": "env0-6qklp-jf98p", "namespace": "env0-agent-pr11529"}
2023-04-04T05:34:30.490Z	INFO	controller-runtime.manager.controller.pod	reconciling pod	{"reconciler group": "", "reconciler kind": "Pod", "name": "env0-jts2r-7fcsg", "namespace": "env0-agent-pr11529"}
2023-04-04T05:34:30.504Z	INFO	controller-runtime.manager.controller.pod	cachedimage patched	{"reconciler group": "", "reconciler kind": "Pod", "name": "env0-jts2r-7fcsg", "namespace": "env0-agent-pr11529", "cachedImage": "ghcr.io-env0-deployment-service-pr11529-sha-532aabb", "sourceImage": "ghcr.io/env0/deployment-service:pr11529-sha-532aabb"}
2023-04-04T05:34:30.504Z	INFO	controller-runtime.manager.controller.pod	reconciled pod	{"reconciler group": "", "reconciler kind": "Pod", "name": "env0-jts2r-7fcsg", "namespace": "env0-agent-pr11529"}
2023-04-04T05:34:37.714Z	INFO	controller-runtime.manager.controller.cachedimage	image cached	{"reconciler group": "kuik.enix.io", "reconciler kind": "CachedImage", "name": "ghcr.io-env0-deployment-service-pr11529-sha-532aabb", "namespace": "", "sourceImage": "ghcr.io/env0/deployment-service:pr11529-sha-532aabb"}
2023-04-04T05:34:37.721Z	INFO	controller-runtime.manager.controller.cachedimage	reconciled cachedimage	{"reconciler group": "kuik.enix.io", "reconciler kind": "CachedImage", "name": "ghcr.io-env0-deployment-service-pr11529-sha-532aabb", "namespace": "", "sourceImage": "ghcr.io/env0/deployment-service:pr11529-sha-532aabb"}
2023-04-04T05:34:37.721Z	INFO	controller-runtime.manager.controller.cachedimage	reconciling cachedimage	{"reconciler group": "kuik.enix.io", "reconciler kind": "CachedImage", "name": "ghcr.io-env0-deployment-service-pr11529-sha-532aabb", "namespace": ""}
2023-04-04T05:34:37.721Z	INFO	controller-runtime.manager.controller.cachedimage	caching image	{"reconciler group": "kuik.enix.io", "reconciler kind": "CachedImage", "name": "ghcr.io-env0-deployment-service-pr11529-sha-532aabb", "namespace": "", "sourceImage": "ghcr.io/env0/deployment-service:pr11529-sha-532aabb"}
2023-04-04T05:34:37.750Z	INFO	controller-runtime.manager.controller.cachedimage	image already present in cache, ignoring	{"reconciler group": "kuik.enix.io", "reconciler kind": "CachedImage", "name": "ghcr.io-env0-deployment-service-pr11529-sha-532aabb", "namespace": "", "sourceImage": "ghcr.io/env0/deployment-service:pr11529-sha-532aabb"}
2023-04-04T05:34:37.754Z	INFO	controller-runtime.manager.controller.cachedimage	reconciling cachedimage	{"reconciler group": "kuik.enix.io", "reconciler kind": "CachedImage", "name": "ghcr.io-env0-deployment-service-pr11529-sha-532aabb", "namespace": ""}
2023-04-04T05:34:37.754Z	INFO	controller-runtime.manager.controller.cachedimage	caching image	{"reconciler group": "kuik.enix.io", "reconciler kind": "CachedImage", "name": "ghcr.io-env0-deployment-service-pr11529-sha-532aabb", "namespace": "", "sourceImage": "ghcr.io/env0/deployment-service:pr11529-sha-532aabb"}
2023-04-04T05:34:37.765Z	INFO	controller-runtime.manager.controller.cachedimage	image already present in cache, ignoring	{"reconciler group": "kuik.enix.io", "reconciler kind": "CachedImage", "name": "ghcr.io-env0-deployment-service-pr11529-sha-532aabb", "namespace": "", "sourceImage": "ghcr.io/env0/deployment-service:pr11529-sha-532aabb"}
2023-04-04T05:34:37.771Z	INFO	controller-runtime.manager.controller.cachedimage	reconciled cachedimage	{"reconciler group": "kuik.enix.io", "reconciler kind": "CachedImage", "name": "ghcr.io-env0-deployment-service-pr11529-sha-532aabb", "namespace": "", "sourceImage": "ghcr.io/env0/deployment-service:pr11529-sha-532aabb"}
2023-04-04T05:34:37.771Z	INFO	controller-runtime.manager.controller.cachedimage	reconciling cachedimage	{"reconciler group": "kuik.enix.io", "reconciler kind": "CachedImage", "name": "ghcr.io-env0-deployment-service-pr11529-sha-532aabb", "namespace": ""}
2023-04-04T05:34:37.771Z	INFO	controller-runtime.manager.controller.cachedimage	caching image	{"reconciler group": "kuik.enix.io", "reconciler kind": "CachedImage", "name": "ghcr.io-env0-deployment-service-pr11529-sha-532aabb", "namespace": "", "sourceImage": "ghcr.io/env0/deployment-service:pr11529-sha-532aabb"}
2023-04-04T05:34:37.784Z	INFO	controller-runtime.manager.controller.cachedimage	image already present in cache, ignoring	{"reconciler group": "kuik.enix.io", "reconciler kind": "CachedImage", "name": "ghcr.io-env0-deployment-service-pr11529-sha-532aabb", "namespace": "", "sourceImage": "ghcr.io/env0/deployment-service:pr11529-sha-532aabb"}
2023-04-04T05:34:37.789Z	INFO	controller-runtime.manager.controller.cachedimage	reconciled cachedimage	{"reconciler group": "kuik.enix.io", "reconciler kind": "CachedImage", "name": "ghcr.io-env0-deployment-service-pr11529-sha-532aabb", "namespace": "", "sourceImage": "ghcr.io/env0/deployment-service:pr11529-sha-532aabb"}
2023-04-04T05:34:39.162Z	INFO	controller-runtime.manager.controller.cachedimage	reconciling cachedimage	{"reconciler group": "kuik.enix.io", "reconciler kind": "CachedImage", "name": "ghcr.io-env0-deployment-service-pr11529-sha-775f533", "namespace": ""}
2023-04-04T05:34:39.163Z	INFO	controller-runtime.manager.controller.cachedimage	caching image	{"reconciler group": "kuik.enix.io", "reconciler kind": "CachedImage", "name": "ghcr.io-env0-deployment-service-pr11529-sha-775f533", "namespace": "", "sourceImage": "ghcr.io/env0/deployment-service:pr11529-sha-775f533"}
2023-04-04T05:34:39.416Z	ERROR	controller-runtime.manager.controller.cachedimage	failed to cache image	{"reconciler group": "kuik.enix.io", "reconciler kind": "CachedImage", "name": "ghcr.io-env0-deployment-service-pr11529-sha-775f533", "namespace": "", "sourceImage": "ghcr.io/env0/deployment-service:pr11529-sha-775f533", "error": "could not find source image"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:298
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.UntilWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:99
```

This also causes a noticeable memory increase

**Comment by paullaffitte** [comment] 2023-04-11 09:23
Hello,

Thanks for reaching us. If the source image is deleted, it looks normal to me that this error happen (`could not find source image`). Then it repeatedly fails because of the nature of a controller in k8s, which have to retry when it fails. But I have to admit that the stacktrace is ugly, since this error is "expected". I will publish a PR to fix this, we are only missing an option in logger configuration as described [here](https://github.com/kubernetes-sigs/kubebuilder/issues/1593#issuecomment-917602472).

The memory increase is also an issue, maybe getting rid of the stacktrace could help, I will try to investigate.

**Comment by Nicolasgouze** [comment] 2023-09-28 14:16
Hello @roni-frantchi , we're closing this issue (works as designed + #72 merged + memory issue tracked in an other thread) !

**Closed by Nicolasgouze** 2023-09-28 14:16 UTC
