### ISSUE TITLE
Expired CachedImages are not being deleted 

### ISSUE THREAD

**Issue by sukumardandu** [enix/kube-image-keeper#396] opened 2024-08-20 06:01 UTC
Old cachedimages are not being cleaned from AWS EBS PVC even with cachedImagesExpiryDelay. 

For example. I have set cachedImagesExpiryDelay to 5 (days). ideally the cached images that are not being used by any containers post the Expiry delay should be deleted/cleaned up as part of the garbage collection.
But in my case, every day for the unused the cachedimages "EXPIRES AT" value is being updated for the next 5th day  and keep happening everyday without being cleaned/deleted. For example lets say today is August 01, 2024, when I list for cachedimages, i can see the unused/old images with "EXPIRES AT" as August 06, 2024, when check again on August 02, 2024 all unused/old images with "EXPIRES AT" as August 07, 2024 and its keep happening without being cleaned/deleted. This is causing all the PVC space to be filled up with lots of unused cached images.

My garbageColletion settings are as follows
      garbageCollection:
        schedule: "0 0 * * 3,6"
        deleteUntagged: false

I am using KUIK version : 1.4.0

**Comment by paullaffitte** [comment] 2024-08-20 12:05
Hello,

kuik 1.4.0 is almost 1 year old and the issue is most probably fixed in more recent versions. Please consider upgrading to the latest version (1.9.3).

**Closed by paullaffitte** 2024-08-20 12:05 UTC
