### ISSUE TITLE
"Sporadic" controller crash when Pods are in "Terminating" status 

### ISSUE THREAD

**Issue by Nicolasgouze** [enix/kube-image-keeper#307] opened 2024-04-08 08:45 UTC
@denniskern : Following our short conversation, can you please provide logs and as much info as possible regarding this issue ? 

On our side : 

- we do not reproduce this issue (tested with 1.6 & 1.7 releases)
- @paullaffitte checked the code. 

We want to be sure we do not miss anything ...

**Comment by paullaffitte** [comment] 2024-04-08 11:36
May be related to #308

**Comment by paullaffitte** [comment] 2024-04-09 12:35
If this issue appeared with version 1.7.0, I think we can confirm that it's the same issue as #308 and thus resolved by #311. @denniskern could you confirm  please?

**Comment by Nicolasgouze** [comment] 2024-04-19 12:08
Hi @denniskern , The PR #311 (including a fix) was merged today, and will be available in next release. I will wait for your test to close this ticket.

**Comment by denniskern** [comment] 2024-04-23 10:31
@Nicolasgouze that we are not pass each other - I need a release to test it :-)

**Comment by spr-mweber3** [comment] 2024-04-25 04:41
@Nicolasgouze @paullaffitte Would you be able to release a beta version so we're able to test that easier? I saw that you did that earlier already. Would help us in getting you the required information more quick.

**Comment by Nicolasgouze** [comment] 2024-04-26 13:18
Hello @spr-mweber3 , we'll release a beta version next monday. stay tuned !

**Comment by paullaffitte** [comment] 2024-04-29 09:07
@denniskern @spr-mweber3  [v1.8.1-beta.1](https://github.com/enix/kube-image-keeper/releases/tag/v1.8.1-beta.1) is available!

**Comment by denniskern** [comment] 2024-05-06 14:38
I tested version v1.8.1-beta.1 and the crash of the controller still exists. The controller crash with this message:

2024-05-06T14:31:02.140Z    ERROR    setup    problem running manager    {"error": "Pod \"kube-prometheus-stack-admission-create-stq7n\" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`,`spec.initContainers[*].image`,`spec.activeDeadlineSeconds`,`spec.tolerations` (only additions to existing tolerations),`spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)\n  core.PodSpec{\n  \t... // 6 identical fields\n  \tActiveDeadlineSeconds:        nil,\n  \tDNSPolicy: \"ClusterFirst\",\n- \tNodeSelector:                 nil,\n+ \tNodeSelector:                 map[string]string{\"workergroup\": \"wg1\"},\n  \tServiceAccountName:           \"kube-prometheus-stack-admission\",\n  \tAutomountServiceAccountToken: nil,\n  \t... // 22 identical fields\n  }\n"}

The pod kube-prometheus-stack-admission-create-stq7n is in state terminating.

**Comment by paullaffitte** [comment] 2024-05-16 14:21
It looks like we have another problem here. But it is very surprising because this error appears in the initialization step as suggests the log "setup problem running manager" and the only update that we do on pods during initialization is no-op (`p.Client.Patch(context.Background(), &pod, client.RawPatch(types.JSONPatchType, []byte("[]")))`). The goal is to trigger to mutating webhook on all existing pods. And in this mutating webhook we only rewrite images and add annotations, which should not be an issue either..

What version of Kubernetes are you using please?

**Comment by denniskern** [comment] 2024-05-17 06:52
We are using 1.27

**Comment by paullaffitte** [comment] 2024-05-22 12:52
Sorry but I cannot reproduce your issue on a cluster in version 1.27. Is there anything specific in your setup? If you could produce a minimal reproducible example it would greatly help.

**Comment by Nicolasgouze** [comment] 2024-05-31 12:14
Hi @denniskern , Do you have any further info to provide so that we try to reproduce & finally correct the issue. 
Thanks in advance !

**Comment by Nicolasgouze** [comment] 2024-06-03 07:26
Hi @denniskern , 

Thanks a lot for the explanation provided !  

It will not come shortly (we currently have other items under development) & would have not given you 100% of the rootcause in your scenario (because of the timing + because "we don't know what we don't know") but we think about working on a "diagnosis tools" that will run on kuik startup in order to check that all cluster pre-requisites are fine before kuik services **really starts**.

**Closed** 2024-06-07 12:06 UTC
Labels: bug

**Comment by devthejo** [comment] 2024-07-23 15:15
Got the same error, also related to kyverno cpol. I think this should not crash the entire controller, just log an error. Let me know if you want I purpose a PR to fix this.
